export const GAME_TYPES = {
  SET_NICKNAME: 'SET_NICKNAME',
  SET_JOIN_CODE: 'SET_JOIN_CODE',
  SET_GAME: 'SET_GAME',
  SET_IS_ADMIN: 'SET_IS_ADMIN',
  SET_CONTEXT: 'SET_CONTEXT',
  SET_TOOL: 'SET_TOOL',
  SET_SIZE: 'SET_SIZE',
  SET_STROKE_COLOR: 'SET_STROKE_COLOR',
  SET_FILL: 'SET_FILL',
  SET_FILL_COLOR: 'SET_FILL_COLOR',

  ADD_ITEM: 'ADD_ITEM',

  CLEAR_ITEMS: 'CLEAR_ITEMS',
  START: 'START',
};
